 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Add a comment to kick off build

trigger:
- master          

resources:
  repositories:
  - repository: self
    ref: 'refs/heads/master'
  - repository: sources
    type: github
    name: keljos/sources
    ref: 'refs/heads/master'
    endpoint: foo
    trigger:
     branches:
      include:
       - master
#  - repository: scripts
#    type: github
#    name: keljos/scripts
#    ref: 'refs/heads/master'
#    endpoint: foo

jobs:
- job: multirepo
  pool: 'Default'
  steps:
  - checkout: self
    clean: true
    path: yaml
  - checkout: sources
    clean: true
    path: src
#  - checkout: scripts
#    clean: true
#    path: scripts
