# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Add a comment to kick off build

trigger:
- master          

resources:
  repositories:
  - repository: self
    ref: 'refs/heads/master'
  - repository: AppTest
    type: git
    name: AppTest/AppTest

jobs:
- job: multirepo
  pool: "Hosted Ubuntu 1604"
  steps:
  - checkout: self
    clean: true
    path: yaml
